Rework into existing action

diff --git a/.github/workflows/misc-tests.yaml b/.github/workflows/misc-tests.yaml
--- a/.github/workflows/misc-tests.yaml
+++ b/.github/workflows/misc-tests.yaml
@@ -1,4 +1,4 @@
-name: Misc tests
+name: Miscellaneous test jobs
 on:
   push:
     branches: [ '*' ]
@@ -26,3 +26,32 @@ jobs:
       - name: Test sandbox configuration
         run: |
           ./tests/ci/run_presandbox_tests.sh
+
+  assert-license-statement-in-pr-description:
+    if: github.repository_owner == 'aws'
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Install jq
+      run: |
+        sudo apt-get update -o Acquire::Languages=none -o Acquire::Translation=none
+        sudo apt-get install -y jq
+
+    - name: Check PR description
+      run: |
+        # Fetches the PR description.
+        PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .body)
+
+        LICENSE_STATEMENT="By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the ISC license."
+
+        echo "PR description: ${PR_DESCRIPTION}"
+        echo "Must contain: ${LICENSE_STATEMENT}"
+
+        # Assert this is the case.
+        if echo "${PR_DESCRIPTION}" | grep -xq "${LICENSE_STATEMENT}"; then
+          echo "PR description contains license statement."
+        else
+          echo "Error: PR description does not contain the required license statement."
+          exit 1
+        fi
